baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Ninth Sense"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
    name = "Ninth Sense"
    description = ""
    email = ""
    phone = "+31 22 222 222"
    address = ""
    year = 2017
    background = ""
    favicon = "images/favicon.png"
    DateForm = "January 2, 2006"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com"
    icon = "fa-facebook-square"
    footer = false
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com"
    icon = "fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
title = "youtube"
url = "https://www.youtube.com"
icon = "fa-youtube"
footer = false
sharethis = true
network = "youtube"
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://www.linkedin.com/in/armstrong-lazenby/"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "email"
	url = "mailto:mail@fitnessimage.com.au"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"